#!/usr/bin/env bash

set -e

NAME=$1
TAG=$2

docker tag ${NAME}:latest quyo/${NAME}:latest
docker tag quyo/${NAME}:latest quyo/${NAME}:${TAG}
docker push quyo/${NAME}:latest
docker push quyo/${NAME}:${TAG}
